### ISSUE TITLE
Package Todo List

### ISSUE THREAD

**Issue by bucaran** [bucaran/wahoo#64]
+ ~~z or equivalent written in fish~~ **→ `fasd`** instead.
+ [ ] hub - aliases git to hub + eventually installation
+ [ ] copy/paste scripts that are multiplatform (OSX, Linux & BSD)
+ ~~ssh-agent~~ **→ `keychain`** instead.
+ [ ] brew completion & setup
+ [ ] gist - publish snippets on https://gist.github.com/
+ [ ] tmux
+ [ ] homebrew
+ [ ] git-flow
+ [ ] gem
+ [ ] pip
+ [ ] npm
+ [ ] node
+ [ ] [cheat-sheets](https://github.com/detailyang/cheat-sheets)

**Comment by gretel** [comment]
>  z or equivalent written in fish
`fasd` is available and working, well, pefectly i'd say. fish integration comes out of the box. i guess we won't get any better
>  ssh-agent
`keychain` is available and working, it is not limited to `ssh` as it supports `gnupg`, too

**Comment by bucaran** [comment]
@gretel :+1:

**Comment by gretel** [comment]
i don't think we should implement something like `serve` because there a free open source thingies doing that well, i just don't come up with the name of the one i prefer to use. besides https://pagekite.net/ is well suited even for pros.

**Comment by gretel** [comment]
`hub` is available and all it does is the alias. i don't feel we should mess with installations

**Comment by bucaran** [comment]
> i don't think we should implement something like serve

I agree. I use a node package `serve` when I need to do this. I find this is not something Wahoo should be concerned with.

**Comment by gretel** [comment]
ah i've found it https://github.com/typicode/katon

**Comment by bucaran** [comment]
What is that and how is it relevant to this discussion?

**Comment by gretel** [comment]
just in relation to the above comment, something like `serve`

**Comment by bucaran** [comment]
Ok. Let's keep discussion to new package ideas and tracking progress on the suggested plugins implementation.

**Comment by gretel** [comment]
if you were expecting folks to stop adding ideas you might possibly just have said so.

**Comment by bucaran** [comment]
What about implementing some of those packages first.

I will work on `pkg-node` for now.
